server:
  port: 8903
spring:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://106.54.118.134:3307/user?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
    mapper-locations: classpath:/mapper/*Mapper.xml
    type-aliases-package: com.he.order.entity
dubbo:
  application:
    name: order
  registry:
    address: zookeeper://106.54.118.134:2181
  scan:
    basePackages: com.he.order.service.impl
  protocol:
      port: 20883